In [1]:
import pandas as pd

data = {
"Name": [
    "Alice", "Bob", "Charlie", "David", "Evelyn",
    "Frank", "Grace", "Henry", "Isla", "Jack",
    "Karen", "Leo", "Mia", "Noah", "Olivia",
    "Paul", "Quinn", "Ruby", "Sam", "Tina"
],
"Age": [25, 32, 37, 29, 41, 28, 34, 45, 26, 31, 39, 27, 33, 36, 30, 42, 24, 38, 35, 29],
"Department": [
    "HR", "Engineering", "Sales", "Marketing", "Engineering",
    "Finance", "Support", "Operations", "HR", "Sales",
    "Engineering", "Support", "Marketing", "Finance", "Operations",
    "Engineering", "HR", "Sales", "Support", "Marketing"
],
"Salary": [
    50000, 75000, 62000, 58000, 80000,
    54000, 52000, 70000, 51000, 64000,
    82000, 53000, 60000, 56000, 68000,
    79000, 49500, 65500, 54500, 61000
],
}

df = pd.DataFrame(data)

In [2]:
df.head()

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000
3    David   29    Marketing   58000
4   Evelyn   41  Engineering   80000

In [3]:
df.tail()

     Name  Age   Department  Salary
15   Paul   42  Engineering   79000
16  Quinn   24           HR   49500
17   Ruby   38        Sales   65500
18    Sam   35      Support   54500
19   Tina   29    Marketing   61000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        20 non-null     str
 1   Age         20 non-null     int64
 2   Department  20 non-null     str
 3   Salary      20 non-null     int64
dtypes: int64(2), str(2)
memory usage: 772.0 bytes

In [6]:
df.shape

(20, 4)

In [7]:
df.loc[12, ["Name", "Age"]]

Name    Mia
Age      33
Name: 12, dtype: object

In [8]:
df.iloc[0:5, 0:3]

      Name  Age   Department
0    Alice   25           HR
1      Bob   32  Engineering
2  Charlie   37        Sales
3    David   29    Marketing
4   Evelyn   41  Engineering

In [10]:
df.iloc[9]["Age"]

np.int64(31)

In [12]:
df.describe()

             Age        Salary
count  20.000000     20.000000
mean   33.050000  62225.000000
std     5.986608  10454.758423
min    24.000000  49500.000000
25%    28.750000  53750.000000
50%    32.500000  60500.000000
75%    37.250000  68500.000000
max    45.000000  82000.000000

In [13]:
df["Department"].value_counts()

Department
Engineering    4
HR             3
Sales          3
Marketing      3
Support        3
Finance        2
Operations     2
Name: count, dtype: int64

In [16]:
df["Age"].mean()

np.float64(33.05)

In [17]:
df["Salary"].max()

np.int64(82000)

In [18]:
df["Name"].nunique()

20

In [19]:
df["Name"].nunique()

20

In [20]:
df.nunique()

Name          20
Age           19
Department     7
Salary        20
dtype: int64